export const FETCH_SEARCH_QUOTES_START = "FETCH_SEARCH_QUOTES_START";
export const FETCH_SEARCH_QUOTES_SUCCES = "FETCH_SEARCH_QUOTES_SUCCES";
export const FETCH_SEARCH_QUOTES_FAILURE = "FETCH_SEARCH_QUOTES_FAILURE";
